anolis: loongarch: anck 6.6 support loongarch
ANBZ: #7099

ANCK-6.6 supports loongarch arch firstly, commit spec and corresponding
scripts and config

Signed-off-by: Gu Mi <gumi@linux.alibaba.com>
Reviewed-by: Juxin Gao <gaojuxin@loongson.cn>
Link: https://gitee.com/anolis/cloud-kernel/pulls/2935

diff --git a/anolis/rpm/kernel.spec.template b/anolis/rpm/kernel.spec.template
--- a/anolis/rpm/kernel.spec.template
+++ b/anolis/rpm/kernel.spec.template
@@ -58,6 +58,12 @@
 # should we do C=1 builds with sparse
 %define with_sparse    %{?_with_sparse:       1} %{?!_with_sparse:       0}
 
+#For loongarch, disable kernel-debug and with_bpftool for unsupport.
+%ifarch loongarch64
+%define with_debug 0
+%define with_bpftool 0
+%endif
+
 %define with_gcov %{?_with_gcov: 1} %{?!_with_gcov: 0}
 
 # turn off debug kernel for gcov builds
@@ -133,6 +139,14 @@
 %define kernel_image arch/arm64/boot/Image.gz
 %endif
 
+%ifarch loongarch64
+%define all_arch_configs %{name}-%{version}-loongarch64*.config
+%define asmarch loongarch
+%define make_target vmlinux
+%define hdrarch loongarch
+%define kernel_image vmlinux
+%endif
+
 # To temporarily exclude an architecture from being built, add it to
 # %%nobuildarches. Do _NOT_ use the ExclusiveArch: line, because if we
 # don't build kernel-headers then the new build system will no longer let
@@ -173,7 +187,7 @@ Release: %{pkg_release}
 Summary: The Linux kernel, based on version %{version}, heavily modified with backports
 # DO NOT CHANGE THE 'ExclusiveArch' LINE TO TEMPORARILY EXCLUDE AN ARCHITECTURE BUILD.
 # SET %%nobuildarches (ABOVE) INSTEAD
-ExclusiveArch: noarch i686 x86_64 aarch64
+ExclusiveArch: noarch i686 x86_64 aarch64 loongarch64
 ExclusiveOS: Linux
 
 
@@ -252,7 +266,8 @@ Source21: kernel-%{version}-aarch64-debug.config
 Source39: kernel-%{version}-x86_64.config
 Source40: kernel-%{version}-x86_64-debug.config
 Source43: generate_bls_conf.sh
-
+Source45: kernel-%{version}-loongarch64.config
+Source46: kernel-%{version}-loongarch64-debug.config
 
 
 # Sources for kernel-tools
@@ -973,13 +988,17 @@ BuildKernel() {
 
 	# Run depmod on the resulting module tree and make sure it isn't broken
 	depmod -b . -aeF ./System.map $KernelVer &> depmod.out
-	if [ -s depmod.out ]; then
-	    echo "Depmod failure"
-	    cat depmod.out
-	    exit 1
-	else
-	    rm depmod.out
-	fi
+	%ifnarch loongarch64
+		if [ -s depmod.out ]; then
+		    echo "Depmod failure"
+		    cat depmod.out
+		    exit 1
+		else
+		    rm depmod.out
+		fi
+	%else
+		rm -rf depmod.out
+	%endif
     else
 	# Ensure important files/directories exist to let the packaging succeed
 	mkdir -p lib/modules/$KernelVer/kernel
